services:
  homebox-classifier:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HOMEBOX_URL=${HOMEBOX_URL:-http://localhost:7745}
      - HOMEBOX_USERNAME=${HOMEBOX_USERNAME}
      - HOMEBOX_PASSWORD=${HOMEBOX_PASSWORD}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
